/**
 * ADWO 2.0 Event Types
 * Core event types for agent communication and WebSocket broadcast
 */

/**
 * Terminal event types for delta-detected output
 */
export type TerminalEventType = "output" | "question" | "error" | "status";

/**
 * Question option extracted from AskUserQuestion pattern
 */
export interface QuestionOption {
  number: number;
  label: string;
  description?: string;
}

/**
 * Metadata extracted from Claude's AskUserQuestion pattern
 * Pattern: ☐ Header + Question text + numbered options + 'Enter to select' footer
 */
export interface QuestionMetadata {
  header: string;
  question: string;
  options: QuestionOption[];
}

/**
 * Normalized terminal event structure
 * Generated by DeltaDetector from raw terminal output
 */
export interface NormalizedTerminalEvent {
  id: string;
  pane_id: string;
  type: TerminalEventType;
  content: string;
  timestamp: string;
  project_id: string;
  /** Question metadata, present when type is 'question' and AskUserQuestion pattern detected */
  question_metadata?: QuestionMetadata;
}

/**
 * Agent event types for the event stream
 */
export type AgentEventType =
  | "agent:start"
  | "agent:end"
  | "agent:error"
  | "tool:start"
  | "tool:end"
  | "tool:error"
  | "workflow:start"
  | "workflow:end"
  | "workflow:error"
  | "message"
  | "thinking"
  | "output";

/**
 * Core agent event structure
 * All events in the system follow this schema
 */
export interface AgentEvent {
  id: string;
  type: AgentEventType;
  timestamp: string;
  agentId?: string;
  workflowId?: string;
  data: Record<string, unknown>;
}

/**
 * Agent state for tracking active agents
 */
export interface AgentState {
  id: string;
  name: string;
  status: "idle" | "running" | "error" | "completed";
  currentPhase?: string;
  startedAt?: string;
  endedAt?: string;
}

/**
 * Workflow state for tracking workflow progress
 */
export interface WorkflowState {
  id: string;
  name: string;
  status: "pending" | "running" | "completed" | "failed";
  currentPhase?: string;
  phases: string[];
  completedPhases: string[];
  startedAt?: string;
  endedAt?: string;
}
